config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
  	resources :phones
  	resources :emails
  end
#               Prefix Verb   URI Pattern                                     Controller#Action
#     contact_phones GET    /contacts/:contact_id/phones(.:format)          phones#index
#                    POST   /contacts/:contact_id/phones(.:format)          phones#create
#  new_contact_phone GET    /contacts/:contact_id/phones/new(.:format)      phones#new
# edit_contact_phone GET    /contacts/:contact_id/phones/:id/edit(.:format) phones#edit
#      contact_phone GET    /contacts/:contact_id/phones/:id(.:format)      phones#show
#                    PATCH  /contacts/:contact_id/phones/:id(.:format)      phones#update
#                    PUT    /contacts/:contact_id/phones/:id(.:format)      phones#update
#                    DELETE /contacts/:contact_id/phones/:id(.:format)      phones#destroy
#     contact_emails GET    /contacts/:contact_id/emails(.:format)          emails#index
#                    POST   /contacts/:contact_id/emails(.:format)          emails#create
#  new_contact_email GET    /contacts/:contact_id/emails/new(.:format)      emails#new
# edit_contact_email GET    /contacts/:contact_id/emails/:id/edit(.:format) emails#edit
#      contact_email GET    /contacts/:contact_id/emails/:id(.:format)      emails#show
#                    PATCH  /contacts/:contact_id/emails/:id(.:format)      emails#update
#                    PUT    /contacts/:contact_id/emails/:id(.:format)      emails#update
#                    DELETE /contacts/:contact_id/emails/:id(.:format)      emails#destroy
#           contacts GET    /contacts(.:format)                             contacts#index
#                    POST   /contacts(.:format)                             contacts#create
#        new_contact GET    /contacts/new(.:format)                         contacts#new
#       edit_contact GET    /contacts/:id/edit(.:format)                    contacts#edit
#            contact GET    /contacts/:id(.:format)                         contacts#show
#                    PATCH  /contacts/:id(.:format)                         contacts#update
#                    PUT    /contacts/:id(.:format)                         contacts#update
#                    DELETE /contacts/:id(.:format)                         contacts#destroy
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :phones
	has_many :emails
	validates :name, presence: true
	validates :name, uniqueness: true
end

app/models/email.rb
class Email < ActiveRecord::Base
	belongs_to :contact
	validates :email, format: {with: /@/, message: "Be sure of the email format"}
end

app/models/phone.rb
class Phone < ActiveRecord::Base
	belongs_to :contact
	validates :phone, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		@contacts = Contact.order(name: :asc)
	end

	def show
		begin
			@contact = Contact.find params[:id]
			@phones = @contact.phones
			@emails = @contact.emails
		rescue ActiveRecord::RecordNotFound
			render 'no_contact_found'
		end
	end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/contacts/index.html.erb
<% if !@contacts.empty? %>
	<h1 class="content__title text-center">Full list of contacts</h1>
	<div class="list-group content__list text-center">
		<% @contacts.each do |contact| %>
		<span class="list-group-item">
			<%= link_to(contact.name, contact_path(contact)) %>
			<!-- Add through javascript the "hover" property to all the button, not just the text -->
		</span>
		<% end %>
	</div>
<% else %>
<h2 class="content__title text-center"> The address book is empty! run rake db:reset to get some examples!</h2>
<% end %>

app/views/contacts/no_contact_found.html.erb
<h1> No contact found </h1>	

app/views/contacts/show.html.erb
<div class="row">
	<ul class="list-group">
		<li class="list-group-item content--rows"><strong><%= @contact.name %></strong></li>
		<li class="list-group-item content--rows"><%= @contact.address %></li>
	</ul>
</div>
<% if ((!@phones.empty?) || (!@emails.empty?)) %>
<div class="row">
	<div class="col-sm-6">
		<p><span class="glyphicon glyphicon-search" aria-hidden="true"></span></p>
		<p class="text-center"><img src="/assets/contacts/phone-icon.png" alt="Phone icon" class="contact-icons"></p>
		<ul class="list-group text-center">
			<% @phones.each do |phone| %>
			<li class="list-group-item content--rows"><%= phone.phone %></li>
			<% end %>
		</ul>
	</div>
	<div class="col-sm-6">
		<p class="text-center"><img src="/assets/contacts/email-icon.png" alt="Phone icon" class="contact-icons"></p>
		<ul class="list-group text-center">
			<% @emails.each do |email| %>
			<li class="list-group-item content--rows"><%= email.email %></li>
			<% end %>
		</ul>
	</div>
</div>
<% end %>
<div class="row">
	<div class="col-sm-3 col-md-offset-5">
		<p>
			<span class="btn btn-default"><%= link_to("Back", contacts_path) %></span>
			<span class="btn btn-default"><%= link_to("Edit", edit_contact_path(@contact)) %></span>
		</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Ruby on Rails Address Book | IH 4th Week exercises</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<header class="col-sm-12 header--main text-center container">
		<h1> RoR Address Book <small>by MrBrown<br></small></h1>
		<div class="col-sm-6 text-center">
		    <button type="button" class="btn btn-success">+ New Contact</button>
		</div>
		<div class="col-sm-6 text-center">
			<div class="form-group header__search">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="Search for a contact, phone or email">
					<span class="input-group-btn">
					<button class="btn btn-success" type="button">Search!</button>
					</span>
				</div>
			</div>
		</div>
    </header>

    <div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2 content--container">
  
				<%= yield %>

			</div>
		</div>
	</div>

	<div class="row">
		<footer class="col-sm-12 footer--main">
		      <p class="footer__text text-center">Copyleft Mr. Brown @ Ironhack bootcamp 2015 - All rights are for you</p>
		</footer>
	</div>
</body>
</html>